/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_prefs (void)
{
  GtkWidget *prefs;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *table1;
  GtkWidget *user_login;
  GtkWidget *label4;
  GtkWidget *label1;
  GtkWidget *vbox2;
  GtkWidget *hbox4;
  GtkWidget *label9;
  GtkObject *nbr_latest_torrent_adj;
  GtkWidget *nbr_latest_torrent;
  GtkWidget *hbox5;
  GtkWidget *label14;
  GtkObject *icon_size_adj;
  GtkWidget *icon_size;
  GtkWidget *hbox6;
  GtkWidget *label15;
  GtkWidget *torrent_syntax;
  GtkWidget *label8;
  GtkWidget *table2;
  GtkWidget *label5;
  GtkWidget *browser;
  GtkWidget *browser_bt;
  GtkWidget *label2;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *dialog_action_area1;
  GtkWidget *applybutton1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  prefs = gtk_dialog_new ();
  gtk_widget_set_name (prefs, "prefs");
  gtk_window_set_title (GTK_WINDOW (prefs), "Preferences");
  gtk_window_set_modal (GTK_WINDOW (prefs), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (prefs), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (prefs), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (prefs), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (prefs)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  table1 = gtk_table_new (1, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  user_login = gtk_entry_new ();
  gtk_widget_set_name (user_login, "user_login");
  gtk_widget_show (user_login);
  gtk_table_attach (GTK_TABLE (table1), user_login, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new ("Login mononoke : ");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label1 = gtk_label_new ("Utilisateur");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox2,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 2);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, TRUE, TRUE, 0);

  label9 = gtk_label_new ("Nombre de torrents : ");
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  nbr_latest_torrent_adj = gtk_adjustment_new (4, 3, 10, 1, 10, 10);
  nbr_latest_torrent = gtk_spin_button_new (GTK_ADJUSTMENT (nbr_latest_torrent_adj), 1, 0);
  gtk_widget_set_name (nbr_latest_torrent, "nbr_latest_torrent");
  gtk_widget_show (nbr_latest_torrent);
  gtk_box_pack_start (GTK_BOX (hbox4), nbr_latest_torrent, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, nbr_latest_torrent, "Le nombre de torrent r\303\251cent a affichier ( n'affecte pas les sorties ni le besoin de sources )", NULL);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox5, TRUE, TRUE, 0);

  label14 = gtk_label_new ("Taille des icones : ");
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);

  icon_size_adj = gtk_adjustment_new (20, 10, 40, 1, 10, 10);
  icon_size = gtk_spin_button_new (GTK_ADJUSTMENT (icon_size_adj), 1, 0);
  gtk_widget_set_name (icon_size, "icon_size");
  gtk_widget_show (icon_size);
  gtk_box_pack_start (GTK_BOX (hbox5), icon_size, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox6, FALSE, FALSE, 0);

  label15 = gtk_label_new ("Syntaxe : ");
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  torrent_syntax = gtk_entry_new ();
  gtk_widget_set_name (torrent_syntax, "torrent_syntax");
  gtk_widget_show (torrent_syntax);
  gtk_box_pack_start (GTK_BOX (hbox6), torrent_syntax, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, torrent_syntax, "Exemple : $(team_icon)$(anime_icon)$(packet_icon) L:$(leechers),S:$(seeders) << $(name) >>\n\n$(team_icon) represente l'image associe avec la team\n$(anime_icon) represente l'image associe avec l'anime\n$(packet_icon) represente l'image expliquant si le download est gratuit ou pas\n$(name),$(team_name),$(cat_name),$(leechers),$(seeders),$(id),$(team_id),$(filename),$(added),$(category)", NULL);

  label8 = gtk_label_new ("Interface");
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label8);

  table2 = gtk_table_new (1, 3, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  label5 = gtk_label_new ("Navigateur : ");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  browser = gtk_entry_new ();
  gtk_widget_set_name (browser, "browser");
  gtk_widget_show (browser);
  gtk_table_attach (GTK_TABLE (table2), browser, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browser_bt = gtk_button_new_with_mnemonic ("...");
  gtk_widget_set_name (browser_bt, "browser_bt");
  gtk_widget_show (browser_bt);
  gtk_table_attach (GTK_TABLE (table2), browser_bt, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label2 = gtk_label_new ("Environnement");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label2);

  label7 = gtk_label_new ("Mononoke-notify 1.0\ndevelop\303\251 par un fan pour des fans :p\n\nVous avez le droits de voter\n et de faire pleins de bisous a BabaLi\nsur http://mononoke-bt.org\n\nRemerciements a ppjunk, EppO, Xrogaan,\naux devs de libcurl, libxml, gtk+ etc...");
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_container_add (GTK_CONTAINER (notebook1), label7);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), label7,
                                      FALSE, TRUE, GTK_PACK_END);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_CENTER);

  label6 = gtk_label_new ("A propos ;)");
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label6);

  dialog_action_area1 = GTK_DIALOG (prefs)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  applybutton1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (applybutton1, "applybutton1");
  gtk_widget_show (applybutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefs), applybutton1, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (applybutton1, GTK_CAN_DEFAULT);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefs), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton1, "okbutton1");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefs), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) prefs, "destroy",
                    G_CALLBACK (on_prefs_destroy),
                    NULL);
  g_signal_connect ((gpointer) browser_bt, "clicked",
                    G_CALLBACK (on_browser_bt_clicked),
                    NULL);
  g_signal_connect ((gpointer) applybutton1, "clicked",
                    G_CALLBACK (on_applybutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefs, prefs, "prefs");
  GLADE_HOOKUP_OBJECT_NO_REF (prefs, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (prefs, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (prefs, table1, "table1");
  GLADE_HOOKUP_OBJECT (prefs, user_login, "user_login");
  GLADE_HOOKUP_OBJECT (prefs, label4, "label4");
  GLADE_HOOKUP_OBJECT (prefs, label1, "label1");
  GLADE_HOOKUP_OBJECT (prefs, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (prefs, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (prefs, label9, "label9");
  GLADE_HOOKUP_OBJECT (prefs, nbr_latest_torrent, "nbr_latest_torrent");
  GLADE_HOOKUP_OBJECT (prefs, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (prefs, label14, "label14");
  GLADE_HOOKUP_OBJECT (prefs, icon_size, "icon_size");
  GLADE_HOOKUP_OBJECT (prefs, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (prefs, label15, "label15");
  GLADE_HOOKUP_OBJECT (prefs, torrent_syntax, "torrent_syntax");
  GLADE_HOOKUP_OBJECT (prefs, label8, "label8");
  GLADE_HOOKUP_OBJECT (prefs, table2, "table2");
  GLADE_HOOKUP_OBJECT (prefs, label5, "label5");
  GLADE_HOOKUP_OBJECT (prefs, browser, "browser");
  GLADE_HOOKUP_OBJECT (prefs, browser_bt, "browser_bt");
  GLADE_HOOKUP_OBJECT (prefs, label2, "label2");
  GLADE_HOOKUP_OBJECT (prefs, label7, "label7");
  GLADE_HOOKUP_OBJECT (prefs, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (prefs, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (prefs, applybutton1, "applybutton1");
  GLADE_HOOKUP_OBJECT (prefs, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (prefs, okbutton1, "okbutton1");
  GLADE_HOOKUP_OBJECT_NO_REF (prefs, tooltips, "tooltips");

  return prefs;
}

